name: Build repo
on:
  push:
    branches: [ Main, Feature ]
  pull_request:
    branches: [ Main, Feature ]
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.7.17
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.17
      - name: Install dependencies
        working-directory: ./
        run: |
          pip install -r requirements.txt
          echo python requirements installed
