name: Build repo
on:
  push:
  pull_request:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install dependencies
        working-directory: ./
        run: |
          pip install -r requirements.txt
          echo python requirements installed
