name: Upload coverage reports to Codecov

on:
  push:
  pull_request:
env:
  ENV: testing
  
jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run Unit Tests and Generate Coverage Reports
        run: |
          pytest --cov=UnitTesting/test_app.py UnitTesting/test_app.py

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
