name: Run Tests On Push
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.10.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.12
      - name: Install dependencies
        working-directory: ./
        run: |
          pip install -r requirements.txt
          echo requirements installed
        
      - name: Run tests
        working-directory: ./UnitTesting
        run: |
          python -m unittest test_app.py
